# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Lukas Peters
description: >- # this means to ignore newlines until "baseurl:"
  Personal Blog.
baseurl: "/" # the subpath of the site
url: "https://www.lukasmpeters.com" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - type: email
      name: Email
      value: lukas.peters0512@gmail.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/lukasmpeters
    - type: github
      name: GitHub
      link: http://github.com/c0untingNumbers
    # - type: rss
    #   name: RSS
    #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
